name: localizations
description: A new Flutter project.
publish_to: 'none'

# flutter gen-l10n   generate class by command line
 
environment:
  sdk: '>=2.19.6 <3.7.12'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2    
  shared_preferences: ^2.1.0
  intl: any
  flutter_localizations:
    sdk: flutter

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true